# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Vadim Abdrashitov
tagline:          'Homepage'
description:      'JavaScript and .NET Developer'

author:
  name:           'Vadim Abdrashitov'
  url:            https://twitter.com/jincod

paginate:         5

github:           https://github.com/jincod

gems:
  - jekyll-gist